# Generated by Django 5.2.4 on 2025-09-08 01:18

import commentPost.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postArticies', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('hidden', 'Hidden')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, default=commentPost.models.Comment.default_thai_time, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=commentPost.models.Comment.default_thai_time, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postArticies.articles')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='commentPost.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'parent'], name='commentPost_article_9cac89_idx'), models.Index(fields=['created_at'], name='commentPost_created_469f72_idx')],
            },
        ),
    ]
